# Generated by Django 4.1.9 on 2023-05-28 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rider_driver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="rider",
            name="tokenized_card",
            field=models.CharField(blank=True, help_text="data created in the payment api", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="rider",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="rider_profile", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
