# Generated by Django 4.1.9 on 2023-05-28 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_driver_user_alter_rider_tokenized_card_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rider",
            old_name="tokenized_card",
            new_name="payment_source",
        ),
    ]
