# Generated by Django 4.1.9 on 2023-05-28 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_rider_driver"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base", models.SmallIntegerField()),
                ("minute", models.SmallIntegerField()),
                ("kilometer", models.SmallIntegerField()),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("starting_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("starting_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("ends", models.DateTimeField(blank=True, null=True)),
                ("final_latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("final_longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "diver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="rides_as_driver", to="users.driver"
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="ride_rates", to="rides.rate"
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="rides_as_rider", to="users.rider"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference", models.CharField(max_length=50)),
                ("minutes_elapsed", models.SmallIntegerField()),
                ("kilometers", models.SmallIntegerField()),
                ("total_amount", models.FloatField()),
                ("transaction_response", models.JSONField()),
                (
                    "ride",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="payment", to="rides.ride"
                    ),
                ),
            ],
        ),
    ]
