# Generated by Django 4.1.9 on 2023-05-28 21:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="diver",
            new_name="driver",
        ),
    ]
