# Generated by Django 4.1.9 on 2023-05-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0002_rename_diver_ride_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="transaction_confirmation",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="payments",
            name="transaction_id",
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="payments",
            name="transaction_response",
            field=models.JSONField(null=True),
        ),
    ]
